config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  namespace :dashboard do
    resources :dummies
  end
  namespace :dashboard do
  get 'home/index'
  resources :marital_statuses
  resources :contacts
  resources :lawsuits
  resources :phones
  resources :forums
  resources :lawyers
  resources :professions
  end

  get 'dashboard', to: 'dashboard/home#index'
  get 'home', to: 'site/home#index'
  get 'history', to: 'site/history#index'
  get 'services', to: 'site/services#index'
  get 'contact', to: 'site/contact#index'

  
  
 
  namespace :site do
    get 'home/index'
  end

  root 'site/home#index'

end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/dashboard/active.rb
class Dashboard::Active < ActiveRecord::Base
  belongs_to :lawsuit
  belongs_to :contact
end

app/models/dashboard/contact.rb
class Dashboard::Contact < ActiveRecord::Base
  attr_accessor :active_ids
  belongs_to :profession
  belongs_to :marital_status
  has_many :actives
  has_many :lawsuits, through: :actives
  has_many :recievers
  has_many :lawsuits, through: :recievers


  #Validates

  validates :name, presence: true, length: {maximum: 50, minimum:3}
  validates :lastname, presence: true, length: {maximum: 50, minimum:3}
  validates :cpf, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 50}

  has_many :phones

  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true


  def fullname
    "#{name} #{lastname}"
  end
  

end

app/models/dashboard/dummy.rb
class Dashboard::Dummy < ActiveRecord::Base
end

app/models/dashboard/forum.rb
class Dashboard::Forum < ActiveRecord::Base
end

app/models/dashboard/lawsuit.rb
# frozen_string_literal: true

class Dashboard::Lawsuit < ActiveRecord::Base
  belongs_to :forum
  belongs_to :lawyer
  has_many :actives
  has_many :contacts, through: :actives
  has_many :recievers
  has_many :contacts, through: :recievers

  #Validations
  validates :autos, :lawyer, :fees, :forum, presence: true

  accepts_nested_attributes_for :actives, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :recievers, reject_if: :all_blank, allow_destroy: true

  def start_time
    self.conciliation_date
  end


end

app/models/dashboard/lawyer.rb
class Dashboard::Lawyer < ActiveRecord::Base
end

app/models/dashboard/marital_status.rb
class Dashboard::MaritalStatus < ActiveRecord::Base
end

app/models/dashboard/phone.rb
class Dashboard::Phone < ActiveRecord::Base
  belongs_to :contact
end

app/models/dashboard/profession.rb
class Dashboard::Profession < ActiveRecord::Base
end

app/models/dashboard/reciever.rb
class Dashboard::Reciever < ActiveRecord::Base
  belongs_to :lawsuit
  belongs_to :contact
end

app/controllers/dashboard/contacts_controller.rb
# frozen_string_literal: true

class Dashboard::ContactsController < DashboardController
  before_action :set_contact, only: %i[show edit update destroy]
  before_action :set_options_for_select, only: %i[new edit update create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Dashboard::Contact.all
    respond_to do |format|
      format.html
      format.json { render json: ContactDatatable.new(params) }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Dashboard::Contact.new
    @contact.phones.build
    
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Dashboard::Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_options_for_select
    @profession_options_for_select = Dashboard::Profession.all.collect { |c| [c.description, c.id] }
    @marital_options_for_select = Dashboard::MaritalStatus.all.collect { |m| [m.description, m.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Dashboard::Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:dashboard_contact).permit(:name, :lastname, :cpf, :rg, :birthdate, :profession_id, :marital_status_id, :address,
                                    :zipcode, :city, :state, :district, phones_attributes: [:number])
  end
end

app/controllers/dashboard/dummies_controller.rb
class Dashboard::DummiesController < ApplicationController
  before_action :set_dashboard_dummy, only: [:show, :edit, :update, :destroy]

  # GET /dashboard/dummies
  # GET /dashboard/dummies.json
  def index
    @dashboard_dummies = Dashboard::Dummy.all
  end

  # GET /dashboard/dummies/1
  # GET /dashboard/dummies/1.json
  def show
  end

  # GET /dashboard/dummies/new
  def new
    @dashboard_dummy = Dashboard::Dummy.new
  end

  # GET /dashboard/dummies/1/edit
  def edit
  end

  # POST /dashboard/dummies
  # POST /dashboard/dummies.json
  def create
    @dashboard_dummy = Dashboard::Dummy.new(dashboard_dummy_params)

    respond_to do |format|
      if @dashboard_dummy.save
        format.html { redirect_to @dashboard_dummy, notice: 'Dummy was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_dummy }
      else
        format.html { render :new }
        format.json { render json: @dashboard_dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/dummies/1
  # PATCH/PUT /dashboard/dummies/1.json
  def update
    respond_to do |format|
      if @dashboard_dummy.update(dashboard_dummy_params)
        format.html { redirect_to @dashboard_dummy, notice: 'Dummy was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_dummy }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/dummies/1
  # DELETE /dashboard/dummies/1.json
  def destroy
    @dashboard_dummy.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_dummies_url, notice: 'Dummy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_dummy
      @dashboard_dummy = Dashboard::Dummy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_dummy_params
      params.require(:dashboard_dummy).permit(:name)
    end
end

app/controllers/dashboard/forums_controller.rb
class Dashboard::ForumsController < DashboardController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Dashboard::Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Dashboard::Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Dashboard::Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render json: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Dashboard::Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:dashboard_forum).permit(:name)
    end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < DashboardController
  def index
    @lawsuits = Dashboard::Lawsuit.all
  end
end

app/controllers/dashboard/lawsuits_controller.rb
# frozen_string_literal: true

class Dashboard::LawsuitsController < DashboardController
  before_action :set_lawsuit, only: %i[show edit update destroy]
  before_action :set_options_for_select

  # GET /lawsuits
  # GET /lawsuits.json
  def index
    @lawsuits = Dashboard::Lawsuit.all
    respond_to do |format|
      format.html
      format.json { render json: LawsuitDatatable.new(params) }
    end
  end

  # GET /lawsuits/1
  # GET /lawsuits/1.json
  def show; end

  # GET /lawsuits/new
  def new
    @lawsuit = Dashboard::Lawsuit.new
    @lawsuit.actives.build
  end

  # GET /lawsuits/1/edit
  def edit
  end

  # POST /lawsuits
  # POST /lawsuits.json
  def create
    @lawsuit = Dashboard::Lawsuit.new(lawsuit_params)

    respond_to do |format|
      if @lawsuit.save
        handle_actives
        handle_recievers
        format.html { redirect_to @lawsuit, notice: 'Lawsuit was successfully created.' }
        format.json { render :show, status: :created, location: @lawsuit }
      else
        format.html { render :new }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawsuits/1
  # PATCH/PUT /lawsuits/1.json
  def update
    @lawsuit.recievers.clear
    respond_to do |format|
      if @lawsuit.update(lawsuit_params)
        @lawsuit.actives.clear
        handle_edit_actives
        format.html { redirect_to @lawsuit, notice: 'Lawsuit was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawsuit }
      else
        format.html { render :edit }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawsuits/1
  # DELETE /lawsuits/1.json
  def destroy
    @lawsuit.destroy
    respond_to do |format|
      format.html { redirect_to lawsuits_url, notice: 'Lawsuit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_options_for_select
    @lawyer_options_for_select = Dashboard::Lawyer.all.collect { |l| [l.name, l.id] }
    @forum_options_for_select = Dashboard::Forum.all.collect { |f| [f.name, f.id] }
    @actives_options_for_select = Dashboard::Contact.all
  end

  def active_ids
    params[:lawsuit][:active_ids]
  end

  def active_ids_for_edit
    params[:lawsuit][:actives_attributes]
  end

  def handle_actives
    # use this to nested attributes (fields_for)
    # params[:lawsuit][:actives_attributes].try(:[], '0').try(:[], :contact_id)
    params[:dashboard_lawsuit][:active_ids]&.each do |a|
      @lawsuit.actives << Dashboard::Active.new(contact_id: a, lawsuit_id: @lawsuit[:id])
    end
  end

  def handle_edit_actives
    active_ids_for_edit&.each do |_k, v|
      if v[:contact_id] != "" and v[:_destroy] == "false"
        @lawsuit.actives << Dashboard::Active.new(contact_id: v[:contact_id], lawsuit_id: @lawsuit[:id])
      end
    end
  end

  def handle_recievers
    params[:dashboard_lawsuit][:reciever_ids]&.each do |a|
      @lawsuit.recievers << Dashboard::Reciever.new(contact_id: a, lawsuit_id: @lawsuit[:id])
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_lawsuit
    @lawsuit = Dashboard::Lawsuit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lawsuit_params
    params.require(:dashboard_lawsuit).permit(:forum_id, :lawyer_id, :fees, :autos, :conciliation_date,
                                    :instruction_date, :interrogation_date, recievers_attributes:[:contact_id, :_destroy])
  end
end

app/controllers/dashboard/lawyers_controller.rb
class Dashboard::LawyersController < DashboardController
  before_action :set_lawyer, only: [:show, :edit, :update, :destroy]

  # GET /lawyers
  # GET /lawyers.json
  def index
    @lawyers = Dashboard::Lawyer.all
  end

  # GET /lawyers/1
  # GET /lawyers/1.json
  def show
  end

  # GET /lawyers/new
  def new
    @lawyer = Dashboard::Lawyer.new
  end

  # GET /lawyers/1/edit
  def edit
  end

  # POST /lawyers
  # POST /lawyers.json
  def create
    @lawyer = Dashboard::Lawyer.new(lawyer_params)

    respond_to do |format|
      if @lawyer.save
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully created.' }
        format.json { render :show, status: :created, location: @lawyer }
      else
        format.html { render :new }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawyers/1
  # PATCH/PUT /lawyers/1.json
  def update
    respond_to do |format|
      if @lawyer.update(lawyer_params)
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawyer }
      else
        format.html { render :edit }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawyers/1
  # DELETE /lawyers/1.json
  def destroy
    @lawyer.destroy
    respond_to do |format|
      format.html { redirect_to lawyers_url, notice: 'Lawyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawyer
      @lawyer = Dashboard::Lawyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lawyer_params
      params.require(:dashboard_lawyer).permit(:name)
    end
end

app/controllers/dashboard/marital_statuses_controller.rb
class Dashboard::MaritalStatusesController < DashboardController
  before_action :set_marital_status, only: [:show, :edit, :update, :destroy]

  # GET /marital_statuses
  # GET /marital_statuses.json
  def index
    @marital_statuses = Dashboard::MaritalStatus.all
  end

  # GET /marital_statuses/1
  # GET /marital_statuses/1.json
  def show
  end

  # GET /marital_statuses/new
  def new
    @marital_status = Dashboard::MaritalStatus.new
  end

  # GET /marital_statuses/1/edit
  def edit
  end

  # POST /marital_statuses
  # POST /marital_statuses.json
  def create
    @marital_status = Dashboard::MaritalStatus.new(marital_status_params)

    respond_to do |format|
      if @marital_status.save
        format.html { redirect_to @marital_status, notice: 'Marital status was successfully created.' }
        format.json { render :show, status: :created, location: @marital_status }
      else
        format.html { render :new }
        format.json { render json: @marital_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marital_statuses/1
  # PATCH/PUT /marital_statuses/1.json
  def update
    respond_to do |format|
      if @marital_status.update(marital_status_params)
        format.html { redirect_to @marital_status, notice: 'Marital status was successfully updated.' }
        format.json { render :show, status: :ok, location: @marital_status }
      else
        format.html { render :edit }
        format.json { render json: @marital_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marital_statuses/1
  # DELETE /marital_statuses/1.json
  def destroy
    @marital_status.destroy
    respond_to do |format|
      format.html { redirect_to marital_statuses_url, notice: 'Marital status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marital_status
      @marital_status = Dashboard::MaritalStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marital_status_params
      params.require(:dashboard_marital_status).permit(:description)
    end
end

app/views/dashboard/lawsuits/_active_fields.html.erb
<div class="nested-fields fields">
  <div class="sixteen wide field">
    <%= f.collection_select :contact_id, Dashboard::Contact.all, :id, :fullname, {include_blank: true},  {placeholder: "Ativo", class: "selectize-generic"} %>
  </div>
  <%= link_to_remove_association f, class:"ui icon button" do %>
  <i class="delete icon"></i>
  <% end %>
</div>

app/views/dashboard/lawsuits/_form.html.erb
<div class="ui container">
  <%= form_for @lawsuit, html: {class: "ui form"} do |f| %>
  <div class="field">
    <label>Informações</label>
    <div class="four fields">
      <div class="field">
        <%= f.text_field :autos, placeholder:"Autos Nº" %>
      </div>
      <div class="field">
        <%= f.select(:forum_id, @forum_options_for_select, {include_blank: true}, {class:"selectize-forum", placeholder: "Vara"})  %>
      </div>
      <div class="field">
        <%= f.select(:lawyer_id, @lawyer_options_for_select, {include_blank: true}, {placeholder: "Advogado", class:"selectize-generic"})  %>
      </div>

      <div class="ui labeled input field">
        <label for="amount" class="ui label">R$</label>
        <%= f.text_field :fees, placeholder:"Honorários" %>
      </div>
    </div>

  </div>
  <div class="field">
    <label>Audiências</label>
    <div class="three fields">
      <div class="field date">
        <div class="ui calendar" id="conciliation-date">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <%= f.text_field :conciliation_date, placeholder:"Data de Conciliação", readonly: true %>
          </div>
        </div>
      </div>
      <div class="field date">
        <div class="ui calendar" id="instruction-date">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <%= f.text_field :instruction_date, placeholder:"Data de Instrução", readonly: true %>
          </div>
        </div>
      </div>
      <div class="field date">
        <div class="ui calendar" id="interrogation-date">
          <div class="ui input left icon">
            <i class="calendar icon"></i>
            <%= f.text_field :interrogation_date, placeholder:"Data de Interrogação", readonly: true %>
          </div>
        </div>
      </div>
    </div>

    <div class="field">
      <label>Partes Interessadas</label>
      <div class="two fields">
        <div class="field">
          <div id="actives">
            <% if local_assigns[:new_action] %>
            <%= f.collection_select :active_ids, Dashboard::Contact.all, :id, :fullname, {include_hidden: false}, {multiple: true, class:"selectize-generic", placeholder: "Ativos"} %>
            <% end %>
            <% if local_assigns[:edit_action] %>
            <%= f.fields_for :actives do |active_fields| %>
            <%= render partial: "active_fields", locals: { f: active_fields } %>
            <% end %>
            <% end %>
          </div>
          <% if local_assigns[:edit_action] %>
          <div class="field">
            <%= link_to_add_association f, :actives, class:"ui right labeled icon button" do %>
            Adicionar Ativo
            <i class="right plus icon"></i>
            <% end %>
          </div>
          <% end %>
        </div>
        <div class="field">
          <div id="recievers">
            <% if local_assigns[:new_action] %>
            <%= f.collection_select :reciever_ids, Dashboard::Contact.all, :id, :fullname, {include_hidden: false}, {multiple: true, class:"selectize-generic", placeholder: "Passivos"} %>
            <% end %>
            <% if local_assigns[:edit_action] %>
            <%= f.fields_for :recievers do |reciever_fields| %>
            <%= render partial: "reciever_fields", locals: { f: reciever_fields } %>
            <% end %>
            <% end %>
            <% if local_assigns[:edit_action] %>
            <div class="field">
              <%= link_to_add_association f, :recievers, class:"ui right labeled icon button" do %>
              Adicionar Passivo
              <i class="right plus icon"></i>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="centered padded grid">
    <% if @lawsuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lawsuit.errors.count, "error") %> prohibited this lawsuit from being saved:</h2>
      <ul>
        <% @lawsuit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
  <%= render partial: "forumModal" %>
  <script>
    $(document).ready(function () {
      var selectizeCallback = null;

      $('.ui.modal.forum-modal')
        .modal({
          onHidden: function (e) {
            if (selectizeCallback != null) {
              selectizeCallback();
              selectizeCallback = null;
            }

            $("#new_dashboard_forum").trigger("reset");
            $.rails.enableFormElements($("#new_dashboard_forum"));
          }
        });

      $("#new_dashboard_forum").on("submit", function (e) {
        e.preventDefault();
        $.ajax({
          dataType: "json",
          method: "POST",
          url: $(this).attr("action"),
          data: $(this).serialize(),
          success: function (response) {
            console.log(response);
            selectizeCallback({ value: response.id, text: response.name });
            selectizeCallback = null;

            $(".ui.modal.forum-modal").modal('toggle');
          }
        })
      });

      $(".selectize-forum").selectize({
        create: function (input, callback) {
          selectizeCallback = callback;
          $(".ui.modal.forum-modal").modal('show');
          $("#dashboard_forum_name").val(input);
        }
      });

      $(".selectize-generic").selectize();

    });

    $(document).on('cocoon:after-insert', function (e, insertedItem, originalEvent) {
      $(insertedItem).find('.selectize-generic').selectize({
        sortField: 'text'
      })
    });

    $('#conciliation-date').calendar({
      type: 'date',
      monthFirst: false,
      text: {
        days: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        today: 'Today',
        now: 'Now',
        am: 'AM',
        pm: 'PM'
      },
    });

    $('#instruction-date').calendar({
      type: 'date',
      monthFirst: false,
      text: {
        days: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        today: 'Today',
        now: 'Now',
        am: 'AM',
        pm: 'PM'
      },
    });

    $('#interrogation-date').calendar({
      type: 'date',
      monthFirst: false,
      text: {
        days: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        today: 'Today',
        now: 'Now',
        am: 'AM',
        pm: 'PM'
      },
    });

  </script>

app/views/dashboard/lawsuits/_passive_fields.html.erb
<div class="nested-fields fields">
  <div class="three wide field">
    <%= f.text_field :name, placeholder: "Nome" %>
  </div>
  
  <%= link_to_remove_association f, class:"ui icon button" do %>
  <i class="delete icon"></i>
  <% end %>
</div>

app/views/dashboard/lawsuits/edit.html.erb
<h1>Editing Lawsuit</h1>

<%= render 'form', edit_action: true %>

<%= link_to 'Show', @lawsuit %> |
<%= link_to 'Back', dashboard_lawsuits_path %>

app/views/dashboard/lawsuits/index.html.erb
<p id="notice"><%= notice %></p>
<div class="ui top attached testef block header clearing segment">
  <label>Lista de Açoes</label>
  <%= link_to  "Nova Ação", new_dashboard_lawsuit_path, class:"ui right floated button pastel" %>
  </div>
<div class="ui bottom attached segment">
<table id="lawsuits-datatable" class="ui celled striped table dataTable" data-source="<%= dashboard_lawsuits_path(format: :json) %>">
  <thead>
    <tr>
      <th>Autos</th>
      <th>Ativos</th>
      <th>Passivos</th>
      <th>Vara</th>
      <th>Advogado</th>
      <th>Remuneração</th>
      <th>Data de Conciliação</th>
      <th>Data de Instrução</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</div>


<br>

app/views/dashboard/lawsuits/new.html.erb
<h1>New Lawsuit</h1>

<%= render 'form', new_action: true %>

<%= link_to 'Back', dashboard_lawsuits_path %>

app/views/dashboard/lawsuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forum:</strong>
  <%= @lawsuit.forum %>
</p>

<p>
  <strong>Lawyer:</strong>
  <%= @lawsuit.lawyer %>
</p>

<p>
  <strong>Fees:</strong>
  <%= @lawsuit.fees %>
</p>

<p>
  <strong>Autos:</strong>
  <%= @lawsuit.autos %>
</p>

<p>
  <strong>Conciliation date:</strong>
  <%= @lawsuit.conciliation_date %>
</p>

<p>
  <strong>Instruction date:</strong>
  <%= @lawsuit.instruction_date %>
</p>



<%= link_to 'Edit', edit_dashboard_lawsuit_path(@lawsuit) %> |
<%= link_to 'Back', dashboard_lawsuits_path %>