config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  namespace :dashboard do
    resources :dummies
  end
  namespace :dashboard do
  get 'home/index'
  resources :marital_statuses
  resources :contacts
  resources :lawsuits
  resources :phones
  resources :forums
  resources :lawyers
  resources :professions
  end

  get 'dashboard', to: 'dashboard/home#index'
  get 'home', to: 'site/home#index'
  get 'history', to: 'site/history#index'
  get 'services', to: 'site/services#index'
  get 'contact', to: 'site/contact#index'

  
  
 
  namespace :site do
    get 'home/index'
  end

  root 'site/home#index'

end

app/controllers/site/contact_controller.rb
class Site::ContactController < SiteController
  def index
  end
end

app/controllers/site/history_controller.rb
class Site::HistoryController < SiteController
  def index
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    
  end
end

app/controllers/site/services_controller.rb
class Site::ServicesController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/helpers/site/contact_helper.rb
module Site::ContactHelper
end

app/helpers/site/history_helper.rb
module Site::HistoryHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/services_helper.rb
module Site::ServicesHelper
end

app/views/site/shared/_fixedMenu.html.erb
<div class="ui container">
  <div class="ui large secondary inverted pointing menu">
    <a class="toc item">
      <i class="sidebar icon"></i>
    </a>
    <%= render partial: "site/shared/menuItems" %>
    <div class="right item">
      <%= link_to "Log in", dashboard_path, class: "ui inverted button" %>
    </div>
  </div>
</div>

app/views/site/shared/_followingMenu.html.erb
<!-- Following Menu -->
<div class="ui large top fixed menu transition hidden">
  <div class="ui container">
    <%= render partial: "site/shared/menuItems" %>
    <div class="right menu">
      <div class="item">
        <%= link_to "Log in", dashboard_path, class: "ui button" %>
      </div>
    </div>
  </div>
</div>

app/views/site/shared/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Sitemap</a>
          <a href="#" class="item">Contact Us</a>
          <a href="#" class="item">Religious Ceremonies</a>
          <a href="#" class="item">Gazebo Plans</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Services</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Banana Pre-Order</a>
          <a href="#" class="item">DNA FAQ</a>
          <a href="#" class="item">How To Access</a>
          <a href="#" class="item">Favorite X-Men</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="ui inverted header">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
  </div>
</div>

app/views/site/shared/_menuItems.html.erb
<%= link_to "Início", root_path, :class => current_class?(root_path)  %>
<%= link_to "História", history_path, :class => current_class?(history_path)  %>
<%= link_to "Serviços", services_path, :class => current_class?(services_path)  %>
<%= link_to "Contatos", contact_path, :class => current_class?(contact_path)  %>