config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  namespace :dashboard do
    resources :dummies
  end
  namespace :dashboard do
  get 'home/index'
  resources :marital_statuses
  resources :contacts
  resources :lawsuits
  resources :phones
  resources :forums
  resources :lawyers
  resources :professions
  end

  get 'dashboard', to: 'dashboard/home#index'
  get 'home', to: 'site/home#index'
  get 'history', to: 'site/history#index'
  get 'services', to: 'site/services#index'
  get 'contact', to: 'site/contact#index'

  
  
 
  namespace :site do
    get 'home/index'
  end

  root 'site/home#index'

end

app/models/dashboard.rb
module Dashboard
  def self.table_name_prefix
    'dashboard_'
  end
end

app/models/dashboard/active.rb
class Dashboard::Active < ActiveRecord::Base
  belongs_to :lawsuit
  belongs_to :contact
end

app/models/dashboard/dummy.rb
class Dashboard::Dummy < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]
  before_action :set_options_for_select, only: %i[new edit update create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    respond_to do |format|
      format.html
      format.json { render json: ContactDatatable.new(params) }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.phones.build
    
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_options_for_select
    @profession_options_for_select = Profession.all.collect { |c| [c.description, c.id] }
    @marital_options_for_select = MaritalStatus.all.collect { |m| [m.description, m.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :lastname, :cpf, :rg, :birthdate, :profession_id, :marital_status_id, :address,
                                    :zipcode, :city, :state, :district, :number)
  end
end

app/controllers/dashboard/contacts_controller.rb
# frozen_string_literal: true

class Dashboard::ContactsController < DashboardController
  before_action :set_contact, only: %i[show edit update destroy]
  before_action :set_options_for_select, only: %i[new edit update create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Dashboard::Contact.all
    respond_to do |format|
      format.html
      format.json { render json: ContactDatatable.new(params) }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Dashboard::Contact.new
    @contact.phones.build
    
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Dashboard::Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_options_for_select
    @profession_options_for_select = Dashboard::Profession.all.collect { |c| [c.description, c.id] }
    @marital_options_for_select = Dashboard::MaritalStatus.all.collect { |m| [m.description, m.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Dashboard::Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:dashboard_contact).permit(:name, :lastname, :cpf, :rg, :birthdate, :profession_id, :marital_status_id, :address,
                                    :zipcode, :city, :state, :district, phones_attributes: [:number])
  end
end

app/controllers/dashboard/dummies_controller.rb
class Dashboard::DummiesController < ApplicationController
  before_action :set_dashboard_dummy, only: [:show, :edit, :update, :destroy]

  # GET /dashboard/dummies
  # GET /dashboard/dummies.json
  def index
    @dashboard_dummies = Dashboard::Dummy.all
  end

  # GET /dashboard/dummies/1
  # GET /dashboard/dummies/1.json
  def show
  end

  # GET /dashboard/dummies/new
  def new
    @dashboard_dummy = Dashboard::Dummy.new
  end

  # GET /dashboard/dummies/1/edit
  def edit
  end

  # POST /dashboard/dummies
  # POST /dashboard/dummies.json
  def create
    @dashboard_dummy = Dashboard::Dummy.new(dashboard_dummy_params)

    respond_to do |format|
      if @dashboard_dummy.save
        format.html { redirect_to @dashboard_dummy, notice: 'Dummy was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_dummy }
      else
        format.html { render :new }
        format.json { render json: @dashboard_dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/dummies/1
  # PATCH/PUT /dashboard/dummies/1.json
  def update
    respond_to do |format|
      if @dashboard_dummy.update(dashboard_dummy_params)
        format.html { redirect_to @dashboard_dummy, notice: 'Dummy was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_dummy }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/dummies/1
  # DELETE /dashboard/dummies/1.json
  def destroy
    @dashboard_dummy.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_dummies_url, notice: 'Dummy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_dummy
      @dashboard_dummy = Dashboard::Dummy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_dummy_params
      params.require(:dashboard_dummy).permit(:name)
    end
end

app/controllers/dashboard/forums_controller.rb
class Dashboard::ForumsController < DashboardController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Dashboard::Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Dashboard::Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Dashboard::Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render json: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Dashboard::Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:dashboard_forum).permit(:name)
    end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < DashboardController
  def index
    @lawsuits = Dashboard::Lawsuit.all
  end
end

app/controllers/dashboard/lawsuits_controller.rb
# frozen_string_literal: true

class Dashboard::LawsuitsController < DashboardController
  before_action :set_lawsuit, only: %i[show edit update destroy]
  before_action :set_options_for_select

  # GET /lawsuits
  # GET /lawsuits.json
  def index
    @lawsuits = Dashboard::Lawsuit.all
    respond_to do |format|
      format.html
      format.json { render json: LawsuitDatatable.new(params) }
    end
  end

  # GET /lawsuits/1
  # GET /lawsuits/1.json
  def show; end

  # GET /lawsuits/new
  def new
    @lawsuit = Dashboard::Lawsuit.new
    @lawsuit.actives.build
  end

  # GET /lawsuits/1/edit
  def edit
  end

  # POST /lawsuits
  # POST /lawsuits.json
  def create
    @lawsuit = Dashboard::Lawsuit.new(lawsuit_params)

    respond_to do |format|
      if @lawsuit.save
        handle_actives
        handle_recievers
        format.html { redirect_to @lawsuit, notice: 'Lawsuit was successfully created.' }
        format.json { render :show, status: :created, location: @lawsuit }
      else
        format.html { render :new }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawsuits/1
  # PATCH/PUT /lawsuits/1.json
  def update
    @lawsuit.recievers.clear
    respond_to do |format|
      if @lawsuit.update(lawsuit_params)
        @lawsuit.actives.clear
        handle_edit_actives
        format.html { redirect_to @lawsuit, notice: 'Lawsuit was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawsuit }
      else
        format.html { render :edit }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawsuits/1
  # DELETE /lawsuits/1.json
  def destroy
    @lawsuit.destroy
    respond_to do |format|
      format.html { redirect_to lawsuits_url, notice: 'Lawsuit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_options_for_select
    @lawyer_options_for_select = Dashboard::Lawyer.all.collect { |l| [l.name, l.id] }
    @forum_options_for_select = Dashboard::Forum.all.collect { |f| [f.name, f.id] }
    @actives_options_for_select = Dashboard::Contact.all
  end

  def active_ids
    params[:lawsuit][:active_ids]
  end

  def active_ids_for_edit
    params[:lawsuit][:actives_attributes]
  end

  def handle_actives
    # use this to nested attributes (fields_for)
    # params[:lawsuit][:actives_attributes].try(:[], '0').try(:[], :contact_id)
    params[:dashboard_lawsuit][:active_ids]&.each do |a|
      @lawsuit.actives << Dashboard::Active.new(contact_id: a, lawsuit_id: @lawsuit[:id])
    end
  end

  def handle_edit_actives
    active_ids_for_edit&.each do |_k, v|
      if v[:contact_id] != "" and v[:_destroy] == "false"
        @lawsuit.actives << Dashboard::Active.new(contact_id: v[:contact_id], lawsuit_id: @lawsuit[:id])
      end
    end
  end

  def handle_recievers
    params[:dashboard_lawsuit][:reciever_ids]&.each do |a|
      @lawsuit.recievers << Dashboard::Reciever.new(contact_id: a, lawsuit_id: @lawsuit[:id])
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_lawsuit
    @lawsuit = Dashboard::Lawsuit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lawsuit_params
    params.require(:dashboard_lawsuit).permit(:forum_id, :lawyer_id, :fees, :autos, :conciliation_date,
                                    :instruction_date, :interrogation_date, recievers_attributes:[:contact_id, :_destroy])
  end
end

app/controllers/dashboard/lawyers_controller.rb
class Dashboard::LawyersController < DashboardController
  before_action :set_lawyer, only: [:show, :edit, :update, :destroy]

  # GET /lawyers
  # GET /lawyers.json
  def index
    @lawyers = Dashboard::Lawyer.all
  end

  # GET /lawyers/1
  # GET /lawyers/1.json
  def show
  end

  # GET /lawyers/new
  def new
    @lawyer = Dashboard::Lawyer.new
  end

  # GET /lawyers/1/edit
  def edit
  end

  # POST /lawyers
  # POST /lawyers.json
  def create
    @lawyer = Dashboard::Lawyer.new(lawyer_params)

    respond_to do |format|
      if @lawyer.save
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully created.' }
        format.json { render :show, status: :created, location: @lawyer }
      else
        format.html { render :new }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawyers/1
  # PATCH/PUT /lawyers/1.json
  def update
    respond_to do |format|
      if @lawyer.update(lawyer_params)
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawyer }
      else
        format.html { render :edit }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawyers/1
  # DELETE /lawyers/1.json
  def destroy
    @lawyer.destroy
    respond_to do |format|
      format.html { redirect_to lawyers_url, notice: 'Lawyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawyer
      @lawyer = Dashboard::Lawyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lawyer_params
      params.require(:dashboard_lawyer).permit(:name)
    end
end

app/controllers/dashboard/phones_controller.rb
class Dashboard::PhonesController < DashboardController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Dashboard::Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Dashboard::Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Dashboard::Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to [:dashboard, @phone], notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to [:dashboard, @phone], notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Dashboard::Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:dashboard_phone).permit(:number, :contact_id)
    end
end

app/views/dashboard/contacts/_form.html.erb
<div class="ui container">
    <%= form_for @contact, html: {class: "ui form"} do |f| %>
    
    <% if @contact.errors.any? %>
    <div class="ui message">
      <div class="header">
        <%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:
      </div>
      <ul class="list">
        <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    
    <div class="field">
      <%= f.label :name %>
      <div class="two fields">
        <div class="field">
          <%= f.text_field :name, placeholder:"Nome" %>
        </div>
        <div class="field">
          <%= f.text_field :lastname, placeholder:"Sobrenome" %>
        </div>
      </div>
    </div>
    
    <div class="field">
      <label>Informações</label>
      <div class="five fields">
        <div class="field">
          <%= f.text_field :cpf, placeholder:"CPF" %>
        </div>
        <div class="field">
          <%= f.text_field :rg, placeholder:"RG" %>
        </div>
        <div class="field">
          <%= f.text_field :birthdate, placeholder:"Data de Nascimento" %>
        </div>
        <div class="field">
            <%= f.select(:profession_id, @profession_options_for_select, {}, { class:"selectize", placeholder: "Profissão" })  %>
        </div>
        <div class="field">
            <%= f.select(:marital_status_id, @marital_options_for_select, {}, { class:"selectize-generic", placeholder: "Estado Civil" })  %>
        </div>
      </div>
    </div>
    
    <div class="field">
      <label>Endereço</label>
      <div class="fields">
        <div class="two wide field">
          <%= f.text_field :zipcode, placeholder:"CEP" %>
        </div>
        <div class="six wide field">
          <%= f.text_field :address, placeholder:"Rua" %>
        </div>
        <div class="two wide field">
          <%= f.text_field :number, placeholder:"Número" %>
        </div>
        <div class="two wide field">
          <%= f.text_field :district, placeholder:"Bairro" %>
        </div>
        <div class="three wide field">
          <%= f.text_field :city, placeholder:"Cidade", readonly: "true" %>
        </div>
        <div class="one wide field">
          <%= f.text_field :state, placeholder:"UF", readonly: "true" %>
        </div>
      </div>
    </div>
    
    <div class="field">
        <label>Telefones</label>
        <div id="phones">
            <%= f.fields_for :phones do |phones_fields| %>
            <%= render partial: "phone_fields", locals: { f: phones_fields } %>
            <% end %>
          </div>
      </div>
    
    
    <div class="field">
      <%= link_to_add_association f, :phones, class:"ui right labeled icon button" do %>
      Adicionar Telefone
      <i class="right plus icon"></i>
      <% end %>
      
    </div>
    <div class="actions ui centered padded grid" style="padding-top: 30px">
        
      <%= button_tag type: 'submit', class: "ui right labeled icon button" do %>
      Salvar
            <i class="check icon" aria-hidden="true"></i>
        <% end %>
    </div>
    <% end %>
    </div>
    <%= render partial: "professionModal"%>
    <script type="text/javascript">
    
      $(document).ready(function () {
    
        function clear_form() {
          $("#dashboard_contact_address").val("");
          $("#dashboard_contact_district").val("");
          $("#dashboard_contact_city").val("");
          $("#dashboard_contact_state").val("");
        }
    
        $("#dashboard_contact_zipcode").blur(function () {
    
          var cep = $(this).val().replace(/\D/g, '');
    
          if (cep != "") {
    
            var validacep = /^[0-9]{8}$/;
    
            if (validacep.test(cep)) {
    
              $("#dashboard_contact_address").val("...");
              $("#dashboard_contact_district").val("...");
              $("#dashboard_contact_city").val("...");
              $("#dashboard_contact_state").val("...");
    
              $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
    
                if (!("erro" in dados)) {
                  $("#dashboard_contact_address").val(dados.logradouro);
                  $("#dashboard_contact_district").val(dados.bairro);
                  $("#dashboard_contact_city").val(dados.localidade);
                  $("#dashboard_contact_state").val(dados.uf);
                }
                else {
                  clear_form();
                  alert("CEP não encontrado.");
                }
              });
            }
            else {
              clear_form();
              alert("Formato de CEP inválido.");
            }
          }
          else {
            clear_form();
          }
        });
      });

      var selectizeCallback = null;
    
      $('.ui.modal.profession-modal')
      .modal({
        onHidden: function(e){
          if (selectizeCallback != null){
            selectizeCallback();
            selectizeCallback = null;
          }
    
          $("#new_dashboard_profession").trigger("reset");
          $.rails.enableFormElements($("#new_dashboard_profession"));
        }
      });
    
      $("#new_dashboard_profession").on("submit", function(e){
        e.preventDefault();
        $.ajax({
          method: "POST",
          dataType: "json",
          url: $(this).attr("action"),
          data: $(this).serialize(),
          success: function(response) {
            selectizeCallback({value: response.id, text: response.description});
            selectizeCallback = null;
    
            $(".ui.modal.profession-modal").modal('hide');
          }
        })
      });
    
      $(".selectize").selectize({
        create: function(input, callback){
          selectizeCallback = callback;
    
          $(".ui.modal.profession-modal").modal('show');
          $("#dashboard_profession_description").val(input);
        }
      });

      $(".selectize-generic").selectize();

    </script>

app/views/dashboard/contacts/_phone_fields.html.erb
<div class="nested-fields fields">
    <div class="three wide field">
      <%= f.text_field :number, placeholder: "Telefone" %>
    </div>
    
    <%= link_to_remove_association f, class:"ui icon button" do %>
    <i class="delete icon"></i>
    <% end %>
  </div>

app/views/dashboard/contacts/_professionModal.html.erb
<div class="ui modal profession-modal">
  <i class="close icon"></i>
  <div class="header">
    Nova Profissão
  </div>
  <div class="content">
    <%= form_for Dashboard::Profession.new, html: {class: "ui form"} do |f| %>
    <% if Dashboard::Profession.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profession.errors.count, "error") %> prohibited this profession from being saved:</h2>

      <ul>
        <% Dashboard::Profession.new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="field">
      <label>Nome da Profissão</label>
      <div class="two fields">
        <div class="field">
          <%= f.text_field :description, placeholder:"Nome" %>
        </div>
      </div>
    </div>
    
  </div>

  <div class="actions">
    <%= f.submit class: "ui button" %>
    <div id="cancel" class="ui button">Cancelar</div>
    
  </div>
  <% end %>
</div>

<script>
    $('#cancel').click(function() {
      $('.ui.modal.profession-modal').modal('toggle');
  });
</script>

app/views/dashboard/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', dashboard_contacts_path %>

app/views/dashboard/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="ui top attached testef block header clearing segment">
<label>Lista de Contatos</label>
<%= link_to  "Novo Contato", new_dashboard_contact_path, class:"ui right floated button pastel" %>
</div>
<div class="ui bottom attached segment">
  <table id="contacts-datatable" class="ui celled striped table dataTable" data-source="<%= dashboard_contacts_path(format: :json) %>">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>CPF</th>
        <th>Cidade</th>
        <th>UF</th>
        <th>Telefones</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<br>

app/views/dashboard/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_contacts_path %>

app/views/dashboard/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact.lastname %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @contact.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @contact.rg %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @contact.birthdate %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @contact.profession %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @contact.marital_status %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @contact.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @contact.state %>
</p>

<p>
  <strong>District:</strong>
  <%= @contact.district %>
</p>

<p>
  <strong>Number:</strong>
  <%= @contact.number %>
</p>

<%= link_to 'Edit', edit_dashboard_contact_path(@contact) %> |
<%= link_to 'Back', dashboard_contacts_path %>